### ISSUE TITLE
Atualização de addons e tradução para ingles.

### ISSUE THREAD

**Issue by KrauseKurt** [xTermWoW/xTermUI_Classic#1]
Opa boa noite, vendo que o github normalmente tem os repositorios em ingles seria legal ter tudo um inglês Paulo.

Os addons tbm estão desatualizados de acordo com o twitch.

**Comment by xTermWoW** [comment]
Cara meu inglês tá bem fraco, se quiser traduzir eu vou deixar esse problema em aberto aqui :)

**Comment by KrauseKurt** [comment]
Ok, vou traduzir esse aqui e o do retail quando você por <3

**Comment by xTermWoW** [comment]
Ah, e fica a vontade de atualizar os addons tbm se quiser, normalmente só devo atualizar eles lá por terça-feira depois da nossa raid.
